add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[0].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[1].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[2].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[3].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[4].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[5].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[6].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[7].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[8].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[9].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[10].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[11].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[12].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[13].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[14].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[15].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[16].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[17].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[18].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[19].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[20].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[21].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[22].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[23].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[24].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[25].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[26].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[27].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[28].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[29].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[30].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
add_wave {{/testbench_top/barvinn_inst/mvu/\mvuarray[0].mvunit /\bankarray[31].db /b/inst/\native_mem_module.blk_mem_gen_v8_4_3_inst /memory}} 
