add_wave_group pito_riscv
    add_wave_group -into pito_riscv soc
        add_wave_group -into soc soc_ext_intf
            add_wave -into soc_ext_intf {{/testbench_top/pito_intf/clk}}
            add_wave -into soc_ext_intf {{/testbench_top/pito_intf/rst_n}}
            add_wave_group -into soc_ext_intf mem_interface
                add_wave -into mem_interface {{/testbench_top/pito_intf/dmem_wdata}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/dmem_rdata}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/dmem_addr}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/dmem_req}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/dmem_we}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/dmem_be}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/imem_wdata}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/imem_rdata}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/imem_addr}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/imem_req}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/imem_we}}
                add_wave -into mem_interface {{/testbench_top/pito_intf/imem_be}}
            add_wave_group -into soc_ext_intf uart
                add_wave -into uart {{/testbench_top/pito_intf/uart_rx}}
                add_wave -into uart {{/testbench_top/pito_intf/uart_tx}}
            add_wave_group -into soc_ext_intf mvu
                add_wave -into mvu {{/testbench_top/pito_intf/mvu_irq}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/paddr}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/pprot}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/psel}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/penable}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/pwrite}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/pwdata}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/pstrb}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/pready}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/prdata}}
                add_wave -into mvu {{/testbench_top/barvinn_inst/soc/mvu_apb/pslverr}}
        add_wave_group -into soc pito
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/mem_out_bound}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/imem_wdata}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/imem_rdata}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/imem_addr}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/imem_req}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/imem_we}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/imem_be}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/dmem_wdata}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/dmem_rdata}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/dmem_addr}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/dmem_req}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/dmem_we}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/pito/dmem_be}}

        add_wave_group -into soc uart
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/rst_n}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/io_read}}
            add_wave -into pito {{/testbench_top/barvinn_inst/soc/io_val}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/tx}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/rx}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/wr}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/rd}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/tx_data}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/rx_data}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/busy}}
            add_wave -into uart {{/testbench_top/barvinn_inst/soc/uart/valid}}
    add_wave_group -into pito_riscv core
        add_wave -into core {{/testbench_top/barvinn_inst/soc/pito/clk}}
        add_wave -into core {{/testbench_top/barvinn_inst/soc/pito/rst_n}}
        add_wave_group -into core FetchStage
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/rv32_pc}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/imem_wdata}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/imem_rdata}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/imem_addr}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/imem_req}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/imem_we}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/imem_be}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/dmem_wdata}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/dmem_rdata}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/dmem_addr}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/dmem_req}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/dmem_we}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/dmem_be}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/rv32_instr}}
            add_wave -into FetchStage {{/testbench_top/barvinn_inst/soc/pito/pc_sel}}
        add_wave_group -into core DecStage
            add_wave_group -into DecStage RegFile
                add_wave -into RegFile {{/testbench_top/barvinn_inst/soc/pito/regfile/clk}} 
                add_wave -into RegFile {{/testbench_top/barvinn_inst/soc/pito/regfile/rsa_hart}} 
                add_wave -into RegFile {{/testbench_top/barvinn_inst/soc/pito/regfile/rsd_hart}} 
                add_wave -into RegFile {{/testbench_top/barvinn_inst/soc/pito/regfile/rd_hart}} 
                add_wave_group -into RegFile RegFileTop
                add_wave -into RegFileTop {{/testbench_top/barvinn_inst/soc/pito/regfile}} 
                add_wave_group -into RegFile RegFile_0
                    add_wave -into RegFile_0 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[0].regfile }} 
                add_wave_group -into RegFile RegFile_1
                    add_wave -into RegFile_1 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[1].regfile }} 
                add_wave_group -into RegFile RegFile_2
                    add_wave -into RegFile_2 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[2].regfile }} 
                add_wave_group -into RegFile RegFile_3
                    add_wave -into RegFile_3 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[3].regfile }} 
                add_wave_group -into RegFile RegFile_4
                    add_wave -into RegFile_4 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[4].regfile }} 
                add_wave_group -into RegFile RegFile_5
                    add_wave -into RegFile_5 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[5].regfile }} 
                add_wave_group -into RegFile RegFile_6
                    add_wave -into RegFile_6 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[6].regfile }} 
                add_wave_group -into RegFile RegFile_7
                    add_wave -into RegFile_7 {{/testbench_top/barvinn_inst/soc/pito/regfile/\genblk1[7].regfile }} 
            add_wave_group -into DecStage Decoder
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_pc}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_rs1}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_rd}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_rs2}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_shamt}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_imm}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_rd1}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_rd2}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_fence_succ}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_fence_pred}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_csr}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_instr_trap}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_alu_op}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_opcode}}
                add_wave -into Decoder {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_instr}}
        add_wave_group -into core EXStage
            add_wave_group -into EXStage Alu
                add_wave -into Alu {{/testbench_top/barvinn_inst/soc/pito/alu_src}}
                add_wave -into Alu {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_rs1}}
                add_wave -into Alu {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_rs2}}
                add_wave -into Alu {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_rd}}
                add_wave -into Alu {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_res}}
                add_wave -into Alu {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_op}}
                add_wave -into Alu {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_z}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_instr}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_rd}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_rs1}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_opcode}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_pc}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_imm}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_rs2_skip}}
            add_wave -into EXStage {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_dmem_addr}}

        add_wave_group -into core WBStage
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_opcode}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_rd}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_out}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_pc}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/is_store}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/is_load}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_is_load}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_instr}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_res}}
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_dmem_addr}}
            
            add_wave -into WBStage {{/testbench_top/barvinn_inst/soc/pito/rv32_dmem_data}}
        add_wave_group -into core WFStage
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_opcode}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_pc}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/pc_sel}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/alu_src}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_i_addr}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_dmem_addr}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_dmem_data}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_dmem_w_en}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_dr_data}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_instr}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_load_val}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_regf_wd}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_skip}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_regf_wen}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_regf_wa}}
            add_wave -into WFStage {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_is_load}}
        add_wave_group -into core Next_PC
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/csr_irq_evt}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/hart_id_i}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/irq_queue_d}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/irq_queue_q}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/irq_data_ptr_d}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/irq_data_ptr_q}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_alu_res}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_rs1}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_imm}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_instr_opcode}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_cur_pc}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_save_pc}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_has_new_pc}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_reg_pc}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_next_pc_val}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_next_pc}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/rv32_new_pc}}
            add_wave -into Next_PC {{/testbench_top/barvinn_inst/soc/pito/rv32_next_pc_cal/IrqQueueDepth}}



    add_wave_group -into pito_riscv decoder
        add_wave -into decoder {{/testbench_top/barvinn_inst/soc/pito/decoder}} 
    add_wave_group -into pito_riscv regfile
        add_wave -into regfile {{/testbench_top/barvinn_inst/soc/pito/regfile}} 
    add_wave_group -into pito_riscv alu
        add_wave -into alu {{/testbench_top/barvinn_inst/soc/pito/alu}} 
    add_wave_group -into pito_riscv pipeline
        add_wave_group -into pipeline pc_counters
            add_wave -into pc_counters {{/testbench_top/barvinn_inst/soc/pito/pc_sel}}
            add_wave -into pc_counters {{/testbench_top/barvinn_inst/soc/pito/rv32_pc}}
            add_wave -into pc_counters {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_pc}}
            add_wave -into pc_counters {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_pc}}
            add_wave -into pc_counters {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_pc}}
            add_wave -into pc_counters {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_pc}}
        add_wave_group -into pipeline instructions
            add_wave -into instructions {{/testbench_top/barvinn_inst/soc/pito/rv32_instr}}
            add_wave -into instructions {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_instr}}
            add_wave -into instructions {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_instr}}
            add_wave -into instructions {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_instr}}
            add_wave -into instructions {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_instr}}
        add_wave_group -into pipeline opcodes
            add_wave -into opcodes {{/testbench_top/barvinn_inst/soc/pito/rv32_instr}}
            add_wave -into opcodes {{/testbench_top/barvinn_inst/soc/pito/rv32_dec_opcode}}
            add_wave -into opcodes {{/testbench_top/barvinn_inst/soc/pito/rv32_ex_opcode}}
            add_wave -into opcodes {{/testbench_top/barvinn_inst/soc/pito/rv32_wb_opcode}}
            add_wave -into opcodes {{/testbench_top/barvinn_inst/soc/pito/rv32_wf_opcode}}
        add_wave_group -into pipeline rs1_2
            add_wave -into rs1_2 {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_rs1}}
            add_wave -into rs1_2 {{/testbench_top/barvinn_inst/soc/pito/rv32_alu_rs2}}
        add_wave_group -into pipeline harts
            add_wave_group -into harts hart_ids
                add_wave -into hart_ids {{/testbench_top/barvinn_inst/soc/pito/rv32_hart_cnt}}
                add_wave -into hart_ids {{/testbench_top/barvinn_inst/soc/pito/rv32_hart_fet_cnt}}
                add_wave -into hart_ids {{/testbench_top/barvinn_inst/soc/pito/rv32_hart_dec_cnt}}
                add_wave -into hart_ids {{/testbench_top/barvinn_inst/soc/pito/rv32_hart_ex_cnt}}
                add_wave -into hart_ids {{/testbench_top/barvinn_inst/soc/pito/rv32_hart_wb_cnt}}
                add_wave -into hart_ids {{/testbench_top/barvinn_inst/soc/pito/rv32_hart_wf_cnt}}
    add_wave_group -into pito_riscv csr
        add_wave_group -into csr csr0
                add_wave -into csr0 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[0].csrfile }}
        add_wave_group -into csr csr1
                add_wave -into csr1 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[1].csrfile }}
        add_wave_group -into csr csr2
                add_wave -into csr2 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[2].csrfile }}
        add_wave_group -into csr csr3
                add_wave -into csr3 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[3].csrfile }}
        add_wave_group -into csr csr4
                add_wave -into csr4 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[4].csrfile }}
        add_wave_group -into csr csr5
                add_wave -into csr5 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[5].csrfile }}
        add_wave_group -into csr csr6
                add_wave -into csr6 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[6].csrfile }}
        add_wave_group -into csr csr7
                add_wave -into csr7 {{/testbench_top/barvinn_inst/soc/pito/csr/\genblk1[7].csrfile }}
    add_wave_group -into pito_riscv mems
        set_property display_limit 3000000 [current_wave_config]
        add_wave_group -into mems i_mem
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/clk_i}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/rst_ni}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/req_i}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/we_i}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/addr_i}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/wdata_i}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/be_i}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/rdata_o}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/sram}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/NumWords}}
            add_wave -into i_mem {{/testbench_top/barvinn_inst/soc/i_mem/ram/NumPorts}}
        add_wave_group -into mems d_mem
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/clk_i}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/rst_ni}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/req_i}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/we_i}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/addr_i}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/wdata_i}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/be_i}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/rdata_o}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/sram}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/NumWords}}
            add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/d_mem/ram/NumPorts}}
            # add_wave -into d_mem {{/testbench_top/barvinn_inst/soc/pito/d_mem/altsyncram_component/mem_data}}

add_wave_group MVU
    add_wave_group -into MVU mvu_ext_if
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/clk}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/rst_n}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/start}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/done}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/irq}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/shacc_clr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/ic_clr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/ichp_clr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrw_addr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrw_word}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrw_en}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/rdc_en}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/rdc_grnt}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/rdc_addr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/rdc_word}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrc_en}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrc_grnt}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrc_addr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrc_word}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrs_en}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrs_addr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrs_word}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrb_en}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrb_addr}}
        add_wave -into mvu_ext_if {{/testbench_top/barvinn_inst/mvu/mvu_ext_if/wrb_word}}
    add_wave_group -into MVU mvu_cfg_if
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/mul_mode}}
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/d_signed}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/w_signed}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/max_en}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/max_clr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/quant_clr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/max_pool}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/quant_msbidx}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/countdown}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/wprecision}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/iprecision}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/oprecision}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/wbaseaddr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/ibaseaddr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/sbaseaddr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/bbaseaddr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/obaseaddr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/omvusel}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/ihpbaseaddr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/ohpbaseaddr}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/ohpmvusel}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/wjump}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/ijump}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/hpjump}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/sjump}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/bjump}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/ojump}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/wlength}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/ilength}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/hplength}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/slength}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/blength}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/olength}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/scaler_b}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/usescaler_mem}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/usebias_mem}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/usepooler4hpout}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/usehpadder}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/shacc_load_sel}} 
        add_wave -into mvu_cfg_if {{/testbench_top/barvinn_inst/mvu/mvu_cfg_if/zigzag_step_sel}} 
