../../../MVU/verification/ip/xilinx/bram64k_64x1024_xilinx.v
../../../MVU/verification/ip/xilinx/bram2m_xilinx.v
../../../MVU/verification/tests/3RD_PARTY_IP/rtl/altera_mf.v
../../lib/mvu/mvu_pkg.sv
../../../MVU/verilog/bram64k.v
../../../MVU/verilog/bank64k.v
../../../MVU/verilog/bram2m.v
../../../MVU/verilog/cdru.v
../../../MVU/verilog/cdwu.v
../../../MVU/verilog/maxpool.v
../../../MVU/verilog/mvp.v
../../../MVU/verilog/mvu.v
../../../MVU/verilog/shacc.v
../../../MVU/verilog/vvp.v
../../../MVU/verilog/interconn.v
../../../MVU/verilog/quantser.v
../../../MVU/verilog/quantser_ctrl.v
../../../MVU/verilog/outagu.v
../../../MVU/verilog/inagu.v
../../../MVU/verilog/agu.v
../../../MVU/verilog/fixedpointscaler.v
../../../MVU/verilog/zigzagu.v
../../../MVU/verilog/controller.v
../../../MVU/verilog/shiftreg.v
../../../MVU/verilog/mvutop.sv
../../lib/rv32/rv32_defines.svh
../../lib/testbench/testbench_macros.svh
../../lib/rv32/rv32_pkg.sv
../../lib/pito/pito_pkg.sv
../../lib/utils/utils.sv
../../lib/rv32/rv32_utils.sv
../../lib/pito/pito_inf.svh
../../lib/pito/pito_monitor.sv
../../lib/testbench/testbench_config.sv
../../lib/testbench/testbench_base.sv
../../lib/mvu/mvu_inf.svh
../../../pito_riscv/vsrc/rv32_imm_gen.sv
../../../pito_riscv/vsrc/rv32_decoder.sv
../../../pito_riscv/vsrc/bram_32Kb.v
../../../pito_riscv/vsrc/rv32_data_memory.sv
../../../pito_riscv/vsrc/rv32_instruction_memory.sv
../../../pito_riscv/vsrc/rv32_alu.sv
../../../pito_riscv/vsrc/rv32_regfile.sv
../../../pito_riscv/vsrc/rv32_barrel_regfiles.sv
../../../pito_riscv/vsrc/rv32_core.sv
../../../pito_riscv/vsrc/rv32_next_pc.sv
../../../pito_riscv/vsrc/rv32_csr.sv
../../../pito_riscv/vsrc/rv32_barrel_csrfiles.sv
../../../vsrc/accelerator.sv
../../../vsrc/data_transposer.sv
../../lib/accel/accel_intf.sv
./core_tester.sv
../../lib/testbench/testbench_top.sv