../../../vsrc/rv32_defines.svh
../../lib/utils/rv32_pkg.sv
../../lib/utils/pito_pkg.sv
../../lib/utils/utils.sv
../../lib/utils/rv32_utils.sv
../../../vsrc/rv32_instr.svh
../../../vsrc/rv32_imm_gen.sv
../../../vsrc/rv32_decoder.sv
../../../vsrc/bram_32Kb.v
../../../vsrc/rv32_data_memory.sv
../../../vsrc/rv32_instruction_memory.sv
../../../vsrc/rv32_alu.sv
../../../vsrc/rv32_regfile.sv
../../../vsrc/rv32_barrel_regfiles.sv
../../../vsrc/rv32_core.sv
../../../vsrc/rv32_next_pc.sv
../../../vsrc/rv32_csr.sv
../../../vsrc/rv32_barrel_csrfiles.sv
./core_tester.sv